use crate::model::{ContactMode, Direction, MotionFamily, Phase, Point};
use crate::spec::{Landmarks, PoseSpec, SpecKind};

const RUN: &[&str] = &[
    "run_front_cross_step_wings_staff",
    "run_front_stride_wings_staff",
    "front_run_charge_wings",
    "run_front_airborne_reach",
    "run_front_airborne_drive",
    "walk_front_left",
    "walk_front_right",
];
const CROUCH: &[&str] = &[
    "front_crouch_guard_wings",
    "front_kneel_staff_brace_wings",
    "front_crouch_hand_plant_wings",
    "front_crouch_staff_planted_wings",
    "front_idle_wings",
    "front_idle",
];
const JUMP: &[&str] = &[
    "front_reaction_jump_wings_staff",
    "front_airborne_fall_back_wings",
    "front_celebrate_jump_wings",
    "front_victory_cast_wings",
    "front_idle_wings",
];
const GUARD: &[&str] = &[
    "front_staff_guard_windup_wings",
    "front_staff_guard_horizontal_wings",
    "front_staff_guard_low_wings",
    "front_magic_staff_thrust_wings",
    "front_staff_block_wings",
    "front_staff_spin_wings",
    "magic_cast",
];
const SOCIAL: &[&str] = &[
    "front_idle_wings",
    "front_greeting_wave_wings",
    "front_thinking_hand_chin_wings",
    "front_explaining_open_hand_wings",
    "front_point_side_wings",
    "front_explaining_both_hands_wings",
    "front_magic_staff_raise_wings",
    "front_sincere_hand_heart_wings",
    "front_playful_kick_wings",
    "front_magic_staff_spark_wings",
    "front_point_direct_wings",
    "front_shush_wings",
    "front_idle",
    "explaining",
    "magic_cast",
];
const FEELINGS: &[&str] = &[
    "feeling_joy_full",
    "feeling_sadness_full",
    "feeling_anger_full",
    "feeling_fear_full",
    "feeling_shame_full",
    "feeling_disgust_full",
    "feeling_surprise_full",
    "feeling_pride_full",
    "feeling_guilt_full",
    "feeling_love_full",
    "front_idle_wings",
];
const FEELING_JOY: &[&str] = &["feeling_joy_full", "feeling_joy_close", "front_idle_wings"];
const FEELING_SADNESS: &[&str] = &[
    "feeling_sadness_full",
    "feeling_sadness_close",
    "feeling_guilt_full",
    "front_idle_wings",
];
const FEELING_ANGER: &[&str] = &[
    "feeling_anger_full",
    "feeling_anger_close",
    "feeling_disgust_full",
    "front_idle_wings",
];
const FEELING_FEAR: &[&str] = &[
    "feeling_fear_full",
    "feeling_fear_close",
    "feeling_surprise_full",
    "front_idle_wings",
];
const FEELING_SHAME: &[&str] = &[
    "feeling_shame_full",
    "feeling_shame_close",
    "feeling_guilt_full",
    "front_idle_wings",
];
const FEELING_DISGUST: &[&str] = &[
    "feeling_disgust_full",
    "feeling_disgust_close",
    "feeling_anger_full",
    "front_idle_wings",
];
const FEELING_SURPRISE: &[&str] = &[
    "feeling_surprise_full",
    "feeling_surprise_close",
    "feeling_fear_full",
    "front_idle_wings",
];
const FEELING_PRIDE: &[&str] = &[
    "feeling_pride_full",
    "feeling_pride_close",
    "feeling_joy_full",
    "front_idle_wings",
];
const FEELING_GUILT: &[&str] = &[
    "feeling_guilt_full",
    "feeling_guilt_close",
    "feeling_shame_full",
    "front_idle_wings",
];
const FEELING_LOVE: &[&str] = &[
    "feeling_love_full",
    "feeling_love_close",
    "feeling_joy_full",
    "front_idle_wings",
];

const fn p(x: i32, y: i32) -> Point {
    Point { x, y }
}

#[allow(clippy::too_many_arguments)]
const fn marks(
    mouth: (i32, i32),
    left_eye: (i32, i32),
    right_eye: (i32, i32),
    left_foot: (i32, i32),
    right_foot: (i32, i32),
    left_hand: (i32, i32),
    right_hand: (i32, i32),
    staff_hand: (i32, i32),
    staff_top: (i32, i32),
) -> Landmarks {
    Landmarks {
        mouth: p(mouth.0, mouth.1),
        left_eye: p(left_eye.0, left_eye.1),
        right_eye: p(right_eye.0, right_eye.1),
        left_foot: p(left_foot.0, left_foot.1),
        right_foot: p(right_foot.0, right_foot.1),
        left_hand: p(left_hand.0, left_hand.1),
        right_hand: p(right_hand.0, right_hand.1),
        staff_hand: p(staff_hand.0, staff_hand.1),
        staff_top: p(staff_top.0, staff_top.1),
    }
}

#[allow(clippy::too_many_arguments)]
const fn geometry(
    order: u32,
    candidate_id: &'static str,
    semantic_id: &'static str,
    rows: u32,
    family: MotionFamily,
    contact_mode: ContactMode,
    phase: Option<Phase>,
    effect: bool,
    landmarks: Landmarks,
    neighbors: &'static [&'static str],
) -> PoseSpec {
    PoseSpec {
        order,
        candidate_id,
        semantic_id,
        kind: SpecKind::Geometry,
        generation_rows: Some(rows),
        family,
        contact_mode,
        phase,
        direction: Direction::South,
        view_family: "front",
        effect,
        landmarks,
        neighbors,
    }
}

const fn face_variant(
    order: u32,
    candidate_id: &'static str,
    semantic_id: &'static str,
    base_semantic_id: &'static str,
    neighbors: &'static [&'static str],
) -> PoseSpec {
    PoseSpec {
        order,
        candidate_id,
        semantic_id,
        kind: SpecKind::FaceVariant { base_semantic_id },
        generation_rows: None,
        family: MotionFamily::GroundAction,
        contact_mode: ContactMode::BothFeet,
        phase: None,
        direction: Direction::South,
        view_family: "front_close_reference",
        effect: false,
        landmarks: marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-16, -43),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        neighbors,
    }
}

const P0: Option<Phase> = Some(Phase {
    numerator: 0,
    denominator: 1,
});
const P1: Option<Phase> = Some(Phase {
    numerator: 1,
    denominator: 4,
});
const P2: Option<Phase> = Some(Phase {
    numerator: 1,
    denominator: 2,
});
const P3: Option<Phase> = Some(Phase {
    numerator: 3,
    denominator: 4,
});

pub(crate) const WJFL_SPECS: [PoseSpec; 50] = [
    geometry(
        31,
        "WJFL-01",
        "run_front_cross_step_wings_staff",
        92,
        MotionFamily::Run,
        ContactMode::Airborne,
        P0,
        false,
        marks(
            (6, -64),
            (2, -73),
            (9, -73),
            (-10, -17),
            (10, -7),
            (-16, -42),
            (26, -46),
            (26, -46),
            (31, -86),
        ),
        RUN,
    ),
    geometry(
        32,
        "WJFL-02",
        "run_front_stride_wings_staff",
        94,
        MotionFamily::Run,
        ContactMode::RightFoot,
        P2,
        false,
        marks(
            (6, -65),
            (3, -72),
            (9, -72),
            (-11, -16),
            (11, -6),
            (-2, -51),
            (25, -52),
            (25, -52),
            (28, -87),
        ),
        RUN,
    ),
    geometry(
        33,
        "WJFL-03",
        "front_crouch_guard_wings",
        86,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (4, -38),
            (0, -45),
            (8, -45),
            (-12, -3),
            (11, -3),
            (-16, -22),
            (25, -32),
            (25, -32),
            (31, -71),
        ),
        CROUCH,
    ),
    geometry(
        34,
        "WJFL-04",
        "front_reaction_jump_wings_staff",
        92,
        MotionFamily::Jump,
        ContactMode::Airborne,
        None,
        false,
        marks(
            (0, -56),
            (-5, -67),
            (5, -67),
            (-12, -7),
            (14, -8),
            (-24, -53),
            (23, -44),
            (23, -44),
            (28, -78),
        ),
        JUMP,
    ),
    geometry(
        35,
        "WJFL-05",
        "front_kneel_staff_brace_wings",
        86,
        MotionFamily::Kneel,
        ContactMode::KneelAndStaff,
        None,
        false,
        marks(
            (0, -44),
            (-4, -52),
            (4, -52),
            (-10, -2),
            (10, -1),
            (-14, -24),
            (17, -31),
            (17, -31),
            (23, -59),
        ),
        CROUCH,
    ),
    geometry(
        36,
        "WJFL-06",
        "front_staff_guard_windup_wings",
        90,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        P1,
        false,
        marks(
            (0, -47),
            (-4, -56),
            (4, -56),
            (-11, -1),
            (12, -1),
            (3, -37),
            (12, -35),
            (12, -35),
            (22, -64),
        ),
        GUARD,
    ),
    geometry(
        37,
        "WJFL-07",
        "front_staff_guard_horizontal_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        P2,
        false,
        marks(
            (0, -57),
            (-5, -68),
            (5, -68),
            (-16, -1),
            (17, -1),
            (-6, -49),
            (13, -37),
            (-6, -49),
            (-21, -65),
        ),
        GUARD,
    ),
    geometry(
        38,
        "WJFL-08",
        "front_staff_guard_low_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        P3,
        false,
        marks(
            (0, -59),
            (-5, -64),
            (5, -64),
            (-7, -1),
            (15, -3),
            (-2, -43),
            (20, -44),
            (-2, -44),
            (13, -80),
        ),
        GUARD,
    ),
    geometry(
        39,
        "WJFL-09",
        "front_crouch_staff_planted_wings",
        84,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (2, -44),
            (-3, -51),
            (6, -51),
            (-14, -1),
            (9, -1),
            (-12, -32),
            (22, -30),
            (22, -30),
            (28, -66),
        ),
        CROUCH,
    ),
    geometry(
        40,
        "WJFL-10",
        "front_victory_cast_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (0, -59),
            (-5, -64),
            (5, -64),
            (-8, -1),
            (11, -1),
            (-18, -63),
            (19, -64),
            (19, -64),
            (19, -90),
        ),
        JUMP,
    ),
    geometry(
        41,
        "WJFL-11",
        "front_run_charge_wings",
        91,
        MotionFamily::Run,
        ContactMode::RightFoot,
        P1,
        false,
        marks(
            (0, -47),
            (-4, -51),
            (6, -51),
            (-8, -7),
            (18, -1),
            (-12, -31),
            (21, -37),
            (21, -37),
            (32, -66),
        ),
        RUN,
    ),
    geometry(
        42,
        "WJFL-12",
        "front_crouch_hand_plant_wings",
        86,
        MotionFamily::Landing,
        ContactMode::HandFootAndStaff,
        None,
        false,
        marks(
            (0, -43),
            (-5, -47),
            (5, -47),
            (-21, -1),
            (14, -3),
            (-18, -2),
            (20, -43),
            (20, -43),
            (32, -68),
        ),
        CROUCH,
    ),
    geometry(
        43,
        "WJFL-13",
        "front_magic_staff_thrust_wings",
        89,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        true,
        marks(
            (7, -45),
            (3, -48),
            (13, -48),
            (-13, -1),
            (21, -2),
            (-9, -39),
            (23, -31),
            (-9, -39),
            (-28, -53),
        ),
        GUARD,
    ),
    geometry(
        44,
        "WJFL-14",
        "front_airborne_fall_back_wings",
        91,
        MotionFamily::Jump,
        ContactMode::Airborne,
        None,
        false,
        marks(
            (0, -51),
            (-5, -55),
            (6, -55),
            (-5, -7),
            (25, -10),
            (-16, -40),
            (20, -45),
            (20, -45),
            (32, -67),
        ),
        JUMP,
    ),
    geometry(
        45,
        "WJFL-15",
        "front_celebrate_staff_up_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (0, -56),
            (-5, -61),
            (5, -61),
            (-9, -1),
            (16, -1),
            (18, -63),
            (-18, -65),
            (-18, -65),
            (-24, -86),
        ),
        SOCIAL,
    ),
    geometry(
        46,
        "WJFL-16",
        "front_staff_block_wings",
        90,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (0, -47),
            (-5, -51),
            (6, -51),
            (-14, -1),
            (19, -1),
            (-19, -37),
            (8, -40),
            (-19, -37),
            (33, -42),
        ),
        GUARD,
    ),
    geometry(
        47,
        "WJFL-17",
        "front_point_direct_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (0, -58),
            (-5, -63),
            (5, -63),
            (-11, -1),
            (17, -1),
            (-23, -59),
            (21, -49),
            (21, -49),
            (27, -83),
        ),
        SOCIAL,
    ),
    geometry(
        48,
        "WJFL-18",
        "front_celebrate_jump_wings",
        92,
        MotionFamily::Jump,
        ContactMode::Airborne,
        None,
        false,
        marks(
            (0, -56),
            (-5, -60),
            (6, -60),
            (-9, -9),
            (13, -7),
            (-15, -68),
            (18, -69),
            (18, -69),
            (25, -86),
        ),
        JUMP,
    ),
    geometry(
        49,
        "WJFL-19",
        "front_shush_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        false,
        marks(
            (0, -60),
            (-5, -65),
            (5, -65),
            (-9, -5),
            (14, -1),
            (-1, -51),
            (21, -50),
            (21, -50),
            (25, -84),
        ),
        SOCIAL,
    ),
    geometry(
        50,
        "WJFL-20",
        "front_staff_spin_wings",
        90,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        true,
        marks(
            (0, -47),
            (-5, -51),
            (6, -51),
            (-11, -1),
            (22, -1),
            (26, -44),
            (-13, -45),
            (-13, -45),
            (-26, -65),
        ),
        GUARD,
    ),
    geometry(
        51,
        "WJFL-21",
        "front_idle_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-15, -40),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        52,
        "WJFL-22",
        "front_greeting_wave_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-20, -62),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        53,
        "WJFL-23",
        "front_thinking_hand_chin_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-1, -52),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        54,
        "WJFL-24",
        "front_explaining_open_hand_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-22, -47),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        55,
        "WJFL-25",
        "front_point_side_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-20, -44),
            (28, -52),
            (-20, -44),
            (-25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        56,
        "WJFL-26",
        "front_explaining_both_hands_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-22, -49),
            (20, -47),
            (20, -47),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        57,
        "WJFL-27",
        "front_magic_staff_raise_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        true,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-17, -40),
            (20, -65),
            (20, -65),
            (24, -90),
        ),
        SOCIAL,
    ),
    geometry(
        58,
        "WJFL-28",
        "front_sincere_hand_heart_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-1, -50),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        59,
        "WJFL-29",
        "front_playful_kick_wings",
        92,
        MotionFamily::GroundAction,
        ContactMode::LeftFoot,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-11, -1),
            (12, -17),
            (-16, -50),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        SOCIAL,
    ),
    geometry(
        60,
        "WJFL-30",
        "front_magic_staff_spark_wings",
        94,
        MotionFamily::GroundAction,
        ContactMode::BothFeet,
        None,
        true,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-18, -46),
            (20, -58),
            (20, -58),
            (24, -90),
        ),
        SOCIAL,
    ),
    geometry(
        61,
        "WJFL-31",
        "feeling_joy_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::LeftFoot,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (11, -11),
            (-21, -62),
            (20, -61),
            (20, -61),
            (25, -88),
        ),
        FEELINGS,
    ),
    geometry(
        62,
        "WJFL-32",
        "feeling_sadness_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -57),
            (-5, -64),
            (5, -64),
            (-8, -1),
            (10, -1),
            (-15, -40),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        63,
        "WJFL-33",
        "feeling_anger_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-10, -1),
            (12, -1),
            (-20, -52),
            (20, -45),
            (20, -45),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        64,
        "WJFL-34",
        "feeling_fear_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-9, -1),
            (11, -1),
            (-22, -49),
            (20, -45),
            (20, -45),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        65,
        "WJFL-35",
        "feeling_shame_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -57),
            (-5, -64),
            (5, -64),
            (-8, -1),
            (10, -1),
            (-3, -54),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        66,
        "WJFL-36",
        "feeling_disgust_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-9, -1),
            (11, -1),
            (-20, -49),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        67,
        "WJFL-37",
        "feeling_surprise_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-9, -1),
            (11, -1),
            (-24, -50),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        68,
        "WJFL-38",
        "feeling_pride_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-10, -1),
            (12, -1),
            (-15, -42),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        69,
        "WJFL-39",
        "feeling_guilt_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        false,
        marks(
            (0, -57),
            (-5, -64),
            (5, -64),
            (-8, -1),
            (10, -1),
            (-4, -48),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    geometry(
        70,
        "WJFL-40",
        "feeling_love_full",
        92,
        MotionFamily::GroundAction,
        ContactMode::BothFeetAndStaff,
        None,
        true,
        marks(
            (0, -58),
            (-5, -65),
            (5, -65),
            (-8, -1),
            (10, -1),
            (-2, -50),
            (20, -44),
            (20, -44),
            (25, -86),
        ),
        FEELINGS,
    ),
    face_variant(
        71,
        "WJFL-51",
        "feeling_joy_close",
        "feeling_joy_full",
        FEELING_JOY,
    ),
    face_variant(
        72,
        "WJFL-52",
        "feeling_sadness_close",
        "feeling_sadness_full",
        FEELING_SADNESS,
    ),
    face_variant(
        73,
        "WJFL-53",
        "feeling_anger_close",
        "feeling_anger_full",
        FEELING_ANGER,
    ),
    face_variant(
        74,
        "WJFL-54",
        "feeling_fear_close",
        "feeling_fear_full",
        FEELING_FEAR,
    ),
    face_variant(
        75,
        "WJFL-55",
        "feeling_shame_close",
        "feeling_shame_full",
        FEELING_SHAME,
    ),
    face_variant(
        76,
        "WJFL-56",
        "feeling_disgust_close",
        "feeling_disgust_full",
        FEELING_DISGUST,
    ),
    face_variant(
        77,
        "WJFL-57",
        "feeling_surprise_close",
        "feeling_surprise_full",
        FEELING_SURPRISE,
    ),
    face_variant(
        78,
        "WJFL-58",
        "feeling_pride_close",
        "feeling_pride_full",
        FEELING_PRIDE,
    ),
    face_variant(
        79,
        "WJFL-59",
        "feeling_guilt_close",
        "feeling_guilt_full",
        FEELING_GUILT,
    ),
    face_variant(
        80,
        "WJFL-60",
        "feeling_love_close",
        "feeling_love_full",
        FEELING_LOVE,
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn fifty_unique_sources_are_ordered_after_the_original_catalog() {
        assert_eq!(WJFL_SPECS.len(), 50);
        assert_eq!(
            WJFL_SPECS
                .iter()
                .map(|spec| spec.candidate_id)
                .collect::<BTreeSet<_>>()
                .len(),
            50
        );
        for (index, spec) in WJFL_SPECS.iter().enumerate() {
            assert_eq!(spec.order, index as u32 + 31);
        }
        assert_eq!(
            WJFL_SPECS
                .iter()
                .filter(|spec| matches!(spec.kind, SpecKind::FaceVariant { .. }))
                .count(),
            10
        );
    }
}
